env:
  node: true
  mocha: true
  es6: true
rules:
  no-extra-semi: 1
  no-inner-declarations: 2
  curly: 2
  no-eval: 2
  no-extend-native: 2
  no-new-wrappers: 2
  no-with: 2
  no-undef: 2
  array-bracket-spacing: [2, never]
  space-before-function-paren: [2, {anonymous: always, named: never}]
  indent: [2, 2, {SwitchCase: 1, VariableDeclarator: 2, CallExpression: {arguments: first}}]
  no-array-constructor: 2
  no-mixed-spaces-and-tabs: 2
  no-new-object: 2
  object-curly-spacing: [2, always]
  semi: [2, never]
  max-len: [1, 80, 2, {ignoreComments: false, ignoreUrls: false}]
